### ISSUE TITLE
js doesn't work

### ISSUE THREAD

**Issue by Fenixol** [philippfrenzel/yii2fullcalendar#149]
After installing plugin there are such errors in the console:

/assets/d21717a9/fullcalendar.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
locale-all.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fullcalendar.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/assets/d21717a9/fullcalendar.print.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fullcalendar.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
locale-all.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
jquery.js:3818 jQuery.Deferred exception: jQuery(...).fullCalendar is not a function TypeError: jQuery(...).fullCalendar is not a function
    at HTMLDocument.<anonymous> (http://idoweddings.local/admin/calendar/index:1028:15)
    at mightThrow (http://idoweddings.local/assets/68db7c94/jquery.js:3534:29)
    at process (http://idoweddings.local/assets/68db7c94/jquery.js:3602:12) undefined
jQuery.Deferred.exceptionHook @ jquery.js:3818
jquery.js:3827 Uncaught TypeError: jQuery(...).fullCalendar is not a function
    at HTMLDocument.<anonymous> (index:1028)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
fullcalendar.print.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
fullcalendar.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

I think it does not find scripts from the plugin.

**Comment by rikcage** [comment]
I think need to use "philippfrenzel / yii2fullcalendar": "3.9.0",
I also have a problem with 4.2.0
